### ISSUE TITLE
path parameterizer fails on remote test controller

### ISSUE THREAD

**Issue by h-parekh** [ndlib/QA_tests#164]
Gatekeeper test to /system/{systemId} fails on testcontroller01 but works on local machine.

      "exception": {
        "class": "TypeError",
        "message": "no implicit conversion of Fixnum into String",
        "backtrace": [
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/path_parameterizer.rb:25:in `sub'",
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/path_parameterizer.rb:25:in `block in call'",
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/path_parameterizer.rb:22:in `each'",
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/path_parameterizer.rb:22:in `call'",
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/request_builder.rb:25:in `apply_parameter_to_parameterized_path!'",
          "/home/app/QA_tests/releases/20170629202019/spec/spec_support/request_builder.rb:15:in `initialize'",
          "/home/app/QA_tests/releases/20170629202019/spec/gatekeeper/integration/int_gatekeeper_spec.rb:7:in `new'",
          "/home/app/QA_tests/releases/20170629202019/spec/gatekeeper/integration/int_gatekeeper_spec.rb:7:in `block (3 levels) in <top (required)>'",

Full logs from [Jenkins job](https://jenkins.library.nd.edu/jenkins/job/QA_tests_deploy_and_run/146/console)

**Comment by h-parekh** [comment]
@jeremyf: Thoughts??

**Comment by h-parekh** [comment]
Did some debugging, it appears like it's working intermittently!

**Comment by h-parekh** [comment]
test data values in shared.yml file were not in quotes (' ')  so Linux was treating them as Hex values.
